### ISSUE TITLE
Options to enable logging in dev mode

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [mikelambert/react-native-fabric-crashlytics#14]
Thank you for creating this lib.

However can you add the option for logging in dev mode? Something like:

```
function init(devMode) {
  if (devMode) {
    // Don't send exceptions from __DEV__, it's way too noisy!
    // Live reloading and hot reloading in particular lead to tons of noise...
    return;
  }
}
```

Thank you.

**Comment by mikelambert** [comment]
Why don't you just do it in your code?
```
if (!devMode) {
  crashlytics.init();
}
```

Sometimes someone may want to temporarily send crashes from dev (for example, to check that crashlytics crash reporting is working, before releasing to the app store)
