### ISSUE TITLE
App does not actually crash

### ISSUE THREAD

**Issue by chetstone** [mikelambert/react-native-fabric-crashlytics#4]
If I don't include crashlytics.init() in my code, and I reference an undefined variable, the app will crash. This is the expected behaviour. However, with crashlytics.init(), the "non-fatal" error will be reported to crashlytics but the app continues to run --- pressing the Back button will reengage the app in the normal manner. This is not expected behaviour. So the code,

```
        if (originalHandler) {
          originalHandler(e);
        }

```

apparently is not running the original handler, or some condition has changed such that the original handler doesn't crash the app. 

I tried moving the call to `originalHandler`inside the `.then` clause so it would not be called until the call to `recordCustomExceptionName` was finished, and that didn't change the behaviour.

**Comment by chetstone** [comment]
The `originalHandler` takes an additional parameter, `isFatal`. Passing this through fixes the problem.

**Comment by mikelambert** [comment]
Pushed 0.1.6 with your fix, thank you for the find/fix.

**Comment by chetstone** [comment]
Hmm. The downside of this, is now I'm seeing 2 reports for each crash in crashlytics. One non-fatal, reported by recordCustomExceptionName with the JS stack, and a fatal crash report showing the Objective C stack, _but with a header also showing the JS stack!_:

```
Unhandled JS Exception: Can't find variable: foobar, stack: onPress@596:5757 _onPress@576:3283 a@103:72 o@100:391 a@100:582 f@97:161 g@97:264 i@106:103 processEventQueue@97:1384 s@156:92 handleTopLevel@156:181 _receiveRootNodeIDEvent@155:615 receiveEvent@155:716 value@28:3098 <unknown>@28:1317 k@28:411 value@28:1289
RCTFatal
 Raw Text
```

I don't know if this is a new feature of Fabric but I hadn't noticed it before. It appears that I actually don't need this component at all, as the default crash report is now showing the (unmapped) JS stack!
