### ISSUE TITLE
Crashes on boot with android, "undefined is not an object (evaluating SMXCrashlytics.crash)"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [mikelambert/react-native-fabric-crashlytics#5]
I'm trying to get this working on Android.

I did "react-native init" and created a new project, then followed Fabric's android instructions (which are incomplete and involved guesswork), and it seemed to build fine.

The I installed your lib, and as soon as it hits the import, the app crashes with a red RN error screen saying "undefined is not an object (evaluating SMXCrashlytics.crash)".

Here's my repo-- what am I doing wrong? https://github.com/GeoffreyPlitt/react_native_minimal/tree/react_native_fabric_crashlytics

**Comment by mikelambert** [comment]
Did you "react native link react-native-fabric" and rebuild?

**Comment by GeoffreyPlitt** [comment]
That worked! How do I force a crash? Other libs seem to have a crash() function...

**Comment by mikelambert** [comment]
throw new Error("test error")

**Comment by GeoffreyPlitt** [comment]
That's a JS exception, not a crash. How do I simulate a native crash?

**Comment by mikelambert** [comment]
https://docs.fabric.io/apple/crashlytics/test-crash.html or https://docs.fabric.io/android/crashlytics/test-crash.html

**Comment by GeoffreyPlitt** [comment]
Actually it looks like https://github.com/mikelambert/react-native-fabric wraps all of this.

Come to think of it, I'm confused, what does your lib add that https://github.com/mikelambert/react-native-fabric doesn't have?

Just the init() function?

Does https://github.com/mikelambert/react-native-fabric work without your init()?

**Comment by mikelambert** [comment]
If you want native crash reporting, you don't need react-native-fabric or react-native-fabric-crashlytics. Just install Fabric/Crashlytics libraries and you're good.

If you want JS exception reporting, react-native-fabric doesn't have enough alone, and yes, I basically just add that init() function that seamlessly hooks into the exceptionhandler. Perhaps I should have upstreamed (or, should upstream) my changes into react-native-fabric-crashlytics, but at the time was newer to JS/NPM and wasn't as clear where to draw those boundaries and how easy it'd be to operate off a personal fork.

**Comment by GeoffreyPlitt** [comment]
I'm still not clear about this: what does your lib do that react-native-fabric does not? Or vice versa?

**Comment by mikelambert** [comment]
Mine wraps/uses react-native-fabric to catch and report JS-level exceptions in react native. react-native-fabric does not do that, AFAIK. You can see this if you look at the contents of my init() function.

**Comment by GeoffreyPlitt** [comment]
Ah OK. Would be nice to put that on your README.
