### ISSUE TITLE
change react-native-fabric to peer-dependency

### ISSUE THREAD

**Issue by atlanteh** [mikelambert/react-native-fabric-crashlytics#6]
I think you should change the react-native-fabric to peer-dependency. Everyone uses this plugin needs to already have react-native-fabric installed. And we might have a different version of fabric which might lead to problems. 
Your module is sort of a "plugin" on top of react-native-fabric.

**Comment by mikelambert** [comment]
Fixed in head.

**Comment by atlanteh** [comment]
Cool, can you please update version here & npm?

**Comment by mikelambert** [comment]
Pushed in 0.1.7.
